import "./globals.css";
import Nav from "./components/Nav.jsx";
import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";

export const metadata = {
  title: "Be-Final-Project",
  description: "Generated by Meli - Randy - Kushtrim - Cihan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
