import "./globals.css";
import Nav from "./components/Nav.jsx";
import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "Be-Final-Project",
  description: "Generated by Meli - Randy - Kushtrim - Cihan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <Nav />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
